name: Maven Dependencies

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  maven-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v3
